spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: GarmothDB
  codec:
    max-in-memory-size: 10485760  # 10MB
  redis:
    host: localhost
    port: 6379

server:
  port: 8080

logging:
  level:
    root: INFO

aliyun:
  sms:
    accessKeyId: 您的AccessKeyId
    accessKeySecret: 您的AccessKeySecret
    signName: 您的短信签名
    templateCode: 您的短信模板CODE


