spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: garmoth
  codec:
    max-in-memory-size: 10485760  # 10MB
  redis:
    host: localhost
    port: 6379

server:
  port: 8080

logging:
  level:
    root: INFO

